include "application.conf"

etl {
  spark {
    app-name = ${?ETL_SPARK_APP_NAME}
    master = ${?ETL_SPARK_MASTER}
    shuffle-partitions = ${?ETL_SPARK_SHUFFLE_PARTITIONS}
  }

  extract {
    flat-files {
      path = ${?ETL_RAW_DATA_PATH}
    }

    databases = [
      {
        name = "postgres-employees"
        enabled = ${?ETL_ENABLE_POSTGRES}
        db-type = "postgres"
        host = ${?ETL_POSTGRES_HOST}
        port = ${?ETL_POSTGRES_PORT}
        database = ${?ETL_POSTGRES_DB}
        user = ${?ETL_POSTGRES_USER}
        password = ${?ETL_POSTGRES_PASSWORD}
        table-or-query = "employees"
        source-tag = "postgres"
      },
      {
        name = "mysql-employees"
        enabled = ${?ETL_ENABLE_MYSQL}
        db-type = "mysql"
        host = ${?ETL_MYSQL_HOST}
        port = ${?ETL_MYSQL_PORT}
        database = ${?ETL_MYSQL_DB}
        user = ${?ETL_MYSQL_USER}
        password = ${?ETL_MYSQL_PASSWORD}
        table-or-query = "employees"
        source-tag = "mysql"
      },
      {
        name = "sqlite-employees"
        enabled = ${?ETL_ENABLE_SQLITE}
        db-type = "sqlite"
        sqlite-file-path = ${?ETL_SQLITE_FILE_PATH}
        table-or-query = "employees"
        source-tag = "sqlite"
      }
    ]
  }

  load {
    output-base-path = ${?ETL_OUTPUT_BASE_PATH}

    warehouse-target {
      enabled = ${?ETL_WAREHOUSE_ENABLED}
      db-type = ${?ETL_WAREHOUSE_DB_TYPE}
      sqlite-file-path = ${?ETL_WAREHOUSE_SQLITE_FILE}
      host = ${?ETL_WAREHOUSE_HOST}
      port = ${?ETL_WAREHOUSE_PORT}
      database = ${?ETL_WAREHOUSE_DB}
      user = ${?ETL_WAREHOUSE_USER}
      password = ${?ETL_WAREHOUSE_PASSWORD}
      schema = ${?ETL_WAREHOUSE_SCHEMA}
    }
  }

  audit {
    output-path = ${?ETL_AUDIT_PATH}
  }

  quarantine {
    base-path = ${?ETL_QUARANTINE_PATH}
  }
}